x_team_git_metrics:
    resource: "@XTeamGitMetricsBundle/Resources/config/routing.yml"
    prefix:   /

x_team_slack_messenger_app:
    resource: "@XTeamSlackMessengerAppBundle/Resources/config/routing.yml"
    prefix:   /

x_team_slack_messenger:
    resource: "@XTeamSlackMessengerBundle/Resources/config/routing.yml"
    prefix:   /

x_team_high_five_slack_bundle:
    resource: "@XTeamHighFiveSlackBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
